# Generated by Django 5.1.3 on 2024-11-27 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webpage',
            new_name='User',
        ),
    ]
