-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 13:54:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema elevatormaintenance
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `elevatormaintenance` ;

-- -----------------------------------------------------
-- Schema elevatormaintenance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elevatormaintenance` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `elevatormaintenance` ;

-- -----------------------------------------------------
-- Table `elevatormaintenance`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elevatormaintenance`.`city` ;

CREATE TABLE IF NOT EXISTS `elevatormaintenance`.`city` (
  `CityId` INT NOT NULL,
  `CityName` CHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`CityId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elevatormaintenance`.`building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elevatormaintenance`.`building` ;

CREATE TABLE IF NOT EXISTS `elevatormaintenance`.`building` (
  `BuildingId` INT NOT NULL,
  `CityId` INT NULL DEFAULT NULL,
  `Floors` INT NULL DEFAULT NULL,
  PRIMARY KEY (`BuildingId`),
  INDEX `CityId` (`CityId` ASC) VISIBLE,
  CONSTRAINT `building_ibfk_1`
    FOREIGN KEY (`CityId`)
    REFERENCES `elevatormaintenance`.`city` (`CityId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elevatormaintenance`.`elevatortype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elevatormaintenance`.`elevatortype` ;

CREATE TABLE IF NOT EXISTS `elevatormaintenance`.`elevatortype` (
  `ElevatorTypeId` INT NOT NULL,
  `TypeName` CHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ElevatorTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elevatormaintenance`.`elevatormodel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elevatormaintenance`.`elevatormodel` ;

CREATE TABLE IF NOT EXISTS `elevatormaintenance`.`elevatormodel` (
  `ElevatorModelId` INT NOT NULL,
  `ModelName` CHAR(100) NULL DEFAULT NULL,
  `Speed` INT NULL DEFAULT NULL,
  `MaxWeight` INT NULL DEFAULT NULL,
  `PeopleLimit` INT NULL DEFAULT NULL,
  `ElevatorTypeId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ElevatorModelId`),
  INDEX `ElevatorTypeId` (`ElevatorTypeId` ASC) VISIBLE,
  CONSTRAINT `elevatormodel_ibfk_1`
    FOREIGN KEY (`ElevatorTypeId`)
    REFERENCES `elevatormaintenance`.`elevatortype` (`ElevatorTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elevatormaintenance`.`elevator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elevatormaintenance`.`elevator` ;

CREATE TABLE IF NOT EXISTS `elevatormaintenance`.`elevator` (
  `ElevatorId` INT NOT NULL,
  `ElevatorModelId` INT NULL DEFAULT NULL,
  `BuildingId` INT NULL DEFAULT NULL,
  `InstallationDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ElevatorId`),
  INDEX `ElevatorModelId` (`ElevatorModelId` ASC) VISIBLE,
  INDEX `BuildingId` (`BuildingId` ASC) VISIBLE,
  CONSTRAINT `elevator_ibfk_1`
    FOREIGN KEY (`ElevatorModelId`)
    REFERENCES `elevatormaintenance`.`elevatormodel` (`ElevatorModelId`),
  CONSTRAINT `elevator_ibfk_2`
    FOREIGN KEY (`BuildingId`)
    REFERENCES `elevatormaintenance`.`building` (`BuildingId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elevatormaintenance`.`employeestatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elevatormaintenance`.`employeestatus` ;

CREATE TABLE IF NOT EXISTS `elevatormaintenance`.`employeestatus` (
  `EmployeeStatusId` INT NOT NULL,
  `StatusDescription` CHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`EmployeeStatusId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elevatormaintenance`.`technician`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elevatormaintenance`.`technician` ;

CREATE TABLE IF NOT EXISTS `elevatormaintenance`.`technician` (
  `EmployeeId` INT NOT NULL,
  `FirstName` CHAR(50) NULL DEFAULT NULL,
  `LastName` CHAR(50) NULL DEFAULT NULL,
  `EmailAddress` CHAR(100) NULL DEFAULT NULL,
  `AnnualSalary` INT NULL DEFAULT NULL,
  `SpecialSkill` CHAR(100) NULL DEFAULT NULL,
  `EmployeeStatusId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`EmployeeId`),
  INDEX `EmployeeStatusId` (`EmployeeStatusId` ASC) VISIBLE,
  CONSTRAINT `technician_ibfk_1`
    FOREIGN KEY (`EmployeeStatusId`)
    REFERENCES `elevatormaintenance`.`employeestatus` (`EmployeeStatusId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elevatormaintenance`.`servicestatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elevatormaintenance`.`servicestatus` ;

CREATE TABLE IF NOT EXISTS `elevatormaintenance`.`servicestatus` (
  `ServiceStatusId` INT NOT NULL,
  `StatusDescription` CHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ServiceStatusId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elevatormaintenance`.`serviceactivity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elevatormaintenance`.`serviceactivity` ;

CREATE TABLE IF NOT EXISTS `elevatormaintenance`.`serviceactivity` (
  `ServiceActivityId` INT NOT NULL,
  `EmployeeId` INT NULL DEFAULT NULL,
  `ElevatorId` INT NULL DEFAULT NULL,
  `ServiceDateTime` DATE NULL DEFAULT NULL,
  `ServiceDescription` CHAR(255) NULL DEFAULT NULL,
  `ServiceStatusId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ServiceActivityId`),
  INDEX `EmployeeId` (`EmployeeId` ASC) VISIBLE,
  INDEX `ElevatorId` (`ElevatorId` ASC) VISIBLE,
  INDEX `ServiceStatusId` (`ServiceStatusId` ASC) VISIBLE,
  CONSTRAINT `serviceactivity_ibfk_1`
    FOREIGN KEY (`EmployeeId`)
    REFERENCES `elevatormaintenance`.`technician` (`EmployeeId`),
  CONSTRAINT `serviceactivity_ibfk_2`
    FOREIGN KEY (`ElevatorId`)
    REFERENCES `elevatormaintenance`.`elevator` (`ElevatorId`),
  CONSTRAINT `serviceactivity_ibfk_3`
    FOREIGN KEY (`ServiceStatusId`)
    REFERENCES `elevatormaintenance`.`servicestatus` (`ServiceStatusId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
